---
name: "iTunes"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "2.0.0.0"
targetAbi: "10.9.0.0"
framework: "net7.0"
overview: "Fetch artist and album images from iTunes."
description: >
  Fetch artist and album images from iTunes
category: "Metadata"
owner: "Shadowghost"
artifacts:
- "HtmlAgilityPack.dll"
- "Jellyfin.Plugin.ITunes.dll"
changelog: >
  1.1.0.0:
    * .NET 7 compatiblity
    * Don't crash if nothing is found
