---
name: "Apple Music"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.1.3"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Fetch images and metadata from Apple Music."
description: >
  Apple Music artist and album images and metadata provider.
category: "Metadata"
owner: "lyarenei"
artifacts:
- "AngleSharp.dll"
- "AngleSharp.XPath.dll"
- "Jellyfin.Plugin.ITunes.dll"
changelog: >
  Improve album identifications
