# $schema: https://json.schemastore.org/github-workflow
name: 'Build and release plugin (dev)'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - jellyfin-10.9.x
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: false
        default: "8.0"
      repo-name:
        type: string
        required: false
        default: "jellyfin-dev"

jobs:
  test:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
    with:
      dotnet-version: ${{ inputs.dotnet-version }}

  build:
    uses: ./.github/workflows/build.yml

  upload-repo:
    if: ${{ contains(github.repository, 'lyarenei/') }}
    needs: build
    uses: ./.github/workflows/upload-repo.yml
    with:
      repo: ${{ inputs.repo-name }}
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      user: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}

  update-manifest:
    if: ${{ contains(github.repository, 'lyarenei/') }}
    needs: upload-repo
    uses: ./.github/workflows/publish.yml
    with:
      repo: ${{ inputs.repo-name }}
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      user: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}
