name: 'Create/Update Release Draft & Release Bump PR'

on:
  push:
    branches:
      - master
      - jellyfin-10.8.x
    paths-ignore:
      - build.yaml
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-prep-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@master
    with:
      repository-name: lyarenei/jellyfin-plugin-itunes
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
