name: 'Test Plugin'

on:
  push:
    branches:
      - master
      - jellyfin-10.8.x
      - jellyfin-10.9.x
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - jellyfin-10.8.x
      - jellyfin-10.9.x
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
